require("plugins.mini-extras")   -- must be first (devicons mock for telescope)
require("plugins.lsp")
require("plugins.completion")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.harpoon")
require("plugins.undotree")
require("plugins.fugitive")
require("plugins.conform")
require("plugins.fidget")
require("plugins.trouble")

